### ISSUE TITLE
Add keyboard shortcut to scroll down

### ISSUE THREAD

**Issue by LudwikJaniuk** [HorzaGobuchul/Amateur-Voat-Enhancements#4]
"Next post" is nice, but if an image is really tall, I need the ability to just scroll up/down. 

(I know there are the arrow keys, but with my hand on J/K, they're far away...)

**Comment by HorzaGobuchul** [comment]
I don't think AVE is needed here. Wouldn't Space and Shift-Space be enough?

**Comment by LudwikJaniuk** [comment]
Hey I had no idea about shift-space. Yeah that is enough. Thanks!
