### ISSUE TITLE
Capital letter key bindings would be nice

### ISSUE THREAD

**Issue by LudwikJaniuk** [HorzaGobuchul/Amateur-Voat-Enhancements#5]
For example, "g" and "G" are not treated as separate keys (I guess support for shift-key would solve this as well).

**Comment by HorzaGobuchul** [comment]
Yes supporting the shift key would do it.

Good idea. I've added it.

**Comment by LudwikJaniuk** [comment]
How much time doe these kind of changes take to get to the web store btw?

**Comment by HorzaGobuchul** [comment]
For the firefox one, the first time I submitted the addon I think it took three months to be reviewed. A 2-3 weeks for Opera and almost no time for Chrome (I don't think the review process is quite the same for Chrome, after you pay a fee you can host your extension very quickly).

Once your addon has been accepted, updating it is very quick.
