### ISSUE TITLE
Chrome manifest seems broken

### ISSUE THREAD

**Issue by LudwikJaniuk** [HorzaGobuchul/Amateur-Voat-Enhancements#9]
Hey, the manifest in the Chrome folder seems broken and misses various pieces. However, since you do seem to have the plugin out on Chrome, does that mean I'm doing the building wrong? How should I get the plugin fired up?

**Comment by HorzaGobuchul** [comment]
You are probably doing everything fine. The file in the repo is indeed broken, it is the pre-build one. The version property is missing because it is added by the build script.

To get the actual manifest.json file, open the .crx file as an archive, it will be in the root folder.

**Comment by LudwikJaniuk** [comment]
Ok. Didn't know what userscript was, thought maybe it was a build system
you were using.

**Comment by LudwikJaniuk** [comment]
So how exactly does building work? The manifest file inside there is indeed valid, but how should I go about packaging it for Chrome? Does the manifest have to be placed in a specific folder, if so, which one? I did use the google general guide, but there were errors.

**Comment by LudwikJaniuk** [comment]
Or, "packaging" as it's called

**Comment by HorzaGobuchul** [comment]
If you are using the extension with Chrome there is no real "building". Simply unpack the .crx file somewhere, go to **chrome://extensions/**, enable "developer mode", then "load unpacked extension".

To pack later, click "pack extension..."

**Comment by LudwikJaniuk** [comment]
In that case, how does code from /src get in to the package? Should I update it manually?

**Comment by HorzaGobuchul** [comment]
I suggest you work directly on these files. The ./src root files go in ./Core and those in ./src/features go in ./Modules. But if you unpacked the .crx files it should already be set up like this

Personally, I work on the files in ./src and my build system copy them over to ./Core and ./Modules.

**Comment by LudwikJaniuk** [comment]
Oh, ok, thenI know how to set it up. I'll see it htere are any more errors

**Comment by LudwikJaniuk** [comment]
Hey, mind sharing that build system tho?

**Comment by HorzaGobuchul** [comment]
Well... It's not that I don't particularly want to. But it's really written ad hoc for my particular folder arrangement (a bit far from the repo's).

I'll have to modify it a bit before releasing it.

**Comment by LudwikJaniuk** [comment]
Oh, don't bother then, no worries.
